server:
  base-url: localhost:8080
  frontend-url: localhost:{ frontPort }

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:{ port }/{ schemaName }?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: { username }
    password: { password }
  jpa:
    defer-datasource-initialization: true
    datasource: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: { email }
    password: { password }
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  header: Authorization
  secret: { secretKey }
  access-token-expire-time: 86400000
  refresh-token-expire-time: 86400000
logging:
  level:
    root: debug

# 환경변수 설정
#  export SENTRY_AUTH_TOKEN={ auth_token }
sentry:
  dsn: { dsn }
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  #debug: true # 디버그 모드
  enable-tracing: true
  send-default-pii: true # 사용자 정보 기록
  environment: development # 개발환경 / environment=production
  #  sample-rate: 1 # 샘플링 비율 1=100% 다 보냄
  #  traces-sample-rate # 트랜잭션 비율 설정
  #  logging: # 범위
  #  minimum-event-level: "WARN"
  #  minimum-breadcrumb-level: "INFO"



